// tools/generate-sprite.js
// Generates sprite.png, sprites.css and updates index.html by replacing <img src="data:..."> with span.sprite elements.
// Requires: sharp

const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const ROOT = path.join(__dirname, '..');
const INDEX_HTML = path.join(ROOT, 'index.html');
const OUT_IMAGES_DIR = path.join(ROOT, 'images');
const OUT_ASSETS_DIR = path.join(ROOT, 'assets');
const SPRITE_PNG = path.join(OUT_ASSETS_DIR, 'sprite.png');
const SPRITES_CSS = path.join(OUT_ASSETS_DIR, 'sprites.css');
const SPRITE_MAP = path.join(OUT_ASSETS_DIR, 'sprite-map.json');

if (!fs.existsSync(INDEX_HTML)) {
  console.error('index.html not found in repository root');
  process.exit(1);
}

if (!fs.existsSync(OUT_IMAGES_DIR)) fs.mkdirSync(OUT_IMAGES_DIR, { recursive: true });
if (!fs.existsSync(OUT_ASSETS_DIR)) fs.mkdirSync(OUT_ASSETS_DIR, { recursive: true });

let html = fs.readFileSync(INDEX_HTML, 'utf8');

// Find all <img ... src="data:..." ...>
const imgTagRegex = /<img\s+([^>]*?)src=("|')(data:(?<mime>image\/(?:png|jpeg|jpg|webp));base64,(?<b64>[A-Za-z0-9+/=]+))(\2)([^>]*?)>/gi;

const images = []; // {filename, mime, b64, classes, alt}
let match;
let counter = 1;
const seenB64 = new Map();

while ((match = imgTagRegex.exec(html)) !== null) {
  const full = match[0];
  const beforeAttrs = match[1] || '';
  const mime = match.groups.mime;
  const b64 = match.groups.b64;
  const afterAttrs = match[7] || '';

  // Extract class and alt from combined attrs
  const attrs = (beforeAttrs + ' ' + (afterAttrs || '')).trim();
  let cls = '';
  let alt = '';
  const classMatch = /class=("|')([^"']+)("|')/i.exec(attrs);
  if (classMatch) cls = classMatch[2];
  const altMatch = /alt=("|')([^"']*)("|')/i.exec(attrs);
  if (altMatch) alt = altMatch[2];

  if (seenB64.has(b64)) {
    // Map to existing filename
    const existing = seenB64.get(b64);
    images.push({ fullTag: full, filename: existing.filename, classes: cls, alt });
    continue;
  }

  const ext = mime === 'image/png' ? 'png' : (mime === 'image/webp' ? 'webp' : (mime === 'image/jpeg' ? 'jpg' : 'bin'));
  const filename = `img-${String(counter).padStart(3, '0')}.${ext}`;
  const outpath = path.join(OUT_IMAGES_DIR, filename);
  fs.writeFileSync(outpath, Buffer.from(b64, 'base64'));

  seenB64.set(b64, { filename });
  images.push({ fullTag: full, filename, classes: cls, alt });
  counter++;
}

if (images.length === 0) {
  console.log('No embedded data:image base64 images found. Exiting.');
  process.exit(0);
}

(async () => {
  try {
    // Read metadata
    const metas = [];
    for (const img of Array.from(new Set(images.map(i => i.filename)))) {
      const p = path.join(OUT_IMAGES_DIR, img);
      const buffer = fs.readFileSync(p);
      const meta = await sharp(buffer).metadata();
      metas.push({ filename: img, width: meta.width, height: meta.height, path: p });
    }

    // Vertical packing
    const spriteWidth = Math.max(...metas.map(m => m.width));
    const spriteHeight = metas.reduce((s, m) => s + m.height, 0);

    let yOffset = 0;
    const composite = [];
    const map = {};
    for (const m of metas) {
      composite.push({ input: m.path, top: yOffset, left: 0 });
      map[m.filename] = { left: 0, top: yOffset, width: m.width, height: m.height };
      yOffset += m.height;
    }

    await sharp({ create: { width: spriteWidth, height: spriteHeight, channels: 4, background: { r:0,g:0,b:0,alpha:0 } } })
      .composite(composite)
      .png()
      .toFile(SPRITE_PNG);

    // Generate sprites.css
    const spriteUrl = path.posix.join('/assets', path.basename(SPRITE_PNG));
    let css = '/* Generated by tools/generate-sprite.js */\n.sprite { background-image: url("' + spriteUrl + '"); background-repeat: no-repeat; display:inline-block; }\n';
    for (const m of metas) {
      const cls = `.sprite-${path.basename(m.filename, path.extname(m.filename))}`;
      const posX = -map[m.filename].left;
      const posY = -map[m.filename].top;
      css += `${cls} { width:${m.width}px; height:${m.height}px; background-position: ${posX}px ${posY}px; }\n`;
    }
    fs.writeFileSync(SPRITES_CSS, css, 'utf8');
    fs.writeFileSync(SPRITE_MAP, JSON.stringify(map, null, 2), 'utf8');

    console.log('Created sprite and mapping. Updating index.html...');

    // Replace <img ... src="data:..."> in original html with <span class="sprite sprite-<name> [orig classes]" role="img" aria-label="alt"></span>
    let newHtml = html;
    for (const entry of images) {
      const name = path.basename(entry.filename, path.extname(entry.filename));
      // escape for regex
      const escaped = entry.fullTag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      // build replacement
      const classPart = (entry.classes ? (entry.classes + ' ') : '');
      const aria = entry.alt ? ` aria-label="${entry.alt.replace(/\"/g,'&quot;')}"` : '';
      const replacement = `<span class="sprite sprite-${name} ${classPart.trim()}" role="img"${aria}></span>`;
      newHtml = newHtml.replace(new RegExp(escaped, 'g'), replacement);
    }

    // Backup original
    fs.writeFileSync(path.join(ROOT, 'index.html.bak'), html, 'utf8');
    fs.writeFileSync(INDEX_HTML, newHtml, 'utf8');

    console.log('index.html updated. Generated files:');
    console.log(' -', SPRITE_PNG);
    console.log(' -', SPRITES_CSS);
    console.log(' -', SPRITE_MAP);

  } catch (err) {
    console.error('Error:', err);
    process.exit(1);
  }
})();
